### PR TITLE
Automated panorama change

### PR DESCRIPTION
**Pull request by hannesa2**
To investigate memory consumption.

Memory is stable on emulator. It only freeze after x attempts. 
image

But logcat shows nothing important (from my point of view)
image

### CODE REVIEW

**Comment by hannesa2** [comment]
Same on a real device Pixel 4
image


At least no memory issue. I'll stop here till a evidence on an Emulator can be observed from your side and showed me

**Comment by ViktorYellows** [comment]
It's weird because on Xiaomi Redmi Note 8  i have memory increase 
https://github.com/ViktorYellows/testPanoramaGl/issues/1#issuecomment-900040281

Btw, any ideas how to fix freeze of application after switching panoramas?

**Comment by hannesa2** [comment]
Please test it with my pull request

**Comment by ViktorYellows** [comment]
Same problem, the app is freezing, i got ANR error after changing panorama 2 times.
Xiaomi Redmi Note 8, Android 9

But if i comment 130 line
`plManager.panorama = panorama`
of course panorama is not displaying, but i haven't got ANR error and app is not freezing

**Comment by hannesa2** [comment]
Try it again and I expect more changes (If I'm not wrong)

**Comment by ViktorYellows** [comment]
Sorry for incorrect question but try again what?

**Comment by hannesa2** [comment]
> Same problem, the app is freezing, i got ANR error after changing panorama 2 times.

I mean this. Try it again and I expect more panorama changes then 2 times (If I'm not wrong)

**Pull request merged**
